source 'http://rubygems.org'

gem 'interactive_editor'
gem 'interactive_rspec'
gem 'konjac'
gem 'pry'
gem 'pry-doc'
gem 'pry-git'
gem 'pry-nav'
gem 'pry-remote'
gem 'pry-stack_explorer'
gem 'term-ansicolor'
gem 'whats_up'
gem 'wirble'
